// Date: 5/28/2016 10:26:40 AM
// Template version 1.1
// Java generated by Techne
// Keep in mind that you still need to fill in some blanks
// - ZeuX

package com.minecolonies.core.client.model;

import net.minecraft.client.model.Model;
import net.minecraft.client.model.geom.ModelPart;
import net.minecraft.client.model.geom.PartPose;
import net.minecraft.client.model.geom.builders.*;
import net.minecraft.client.model.HumanoidModel;
import net.minecraft.client.renderer.rendertype.RenderTypes;
import net.minecraft.util.Unit;

/**
 * PORT26: {@code Model} is generic over the render state now (mirrors vanilla
 * {@code Model<Unit>} usage) and takes the root part + render type function in the
 * constructor — the old single-argument constructor and the renderToBuffer override
 * (final in 26.1) are gone; the base implementation renders the whole root tree, so
 * the vanilla humanoid leftovers ("body"/"hat") are cleared in {@link #createMesh()}
 * to keep exactly the part set the 1.21.1 manual renderToBuffer used to draw.
 */
public class ScarecrowModel extends Model<Unit>
{
    //fields
    ModelPart head;
    ModelPart post;
    ModelPart leftArmPeg;
    ModelPart rightArmPeg;
    ModelPart torso;
    ModelPart rightLegPeg;
    ModelPart leftLegPeg;
    ModelPart leftArm;
    ModelPart rightArm;
    ModelPart rightLeg;
    ModelPart leftLeg;

    public ScarecrowModel(final ModelPart part)
    {
        super(part, RenderTypes::entitySolid);
        head = part.getChild("head");
        post = part.getChild("post");
        leftArmPeg = part.getChild("leftArmPeg");
        rightArmPeg = part.getChild("rightArmPeg");
        torso = part.getChild("torso");
        rightLegPeg = part.getChild("rightLegPeg");
        leftLegPeg = part.getChild("leftLegPeg");
        leftArm = part.getChild("left_arm");
        rightArm = part.getChild("right_arm");
        rightLeg = part.getChild("right_leg");
        leftLeg = part.getChild("left_leg");
    }

    public static LayerDefinition createMesh()
    {
        MeshDefinition meshdefinition = HumanoidModel.createMesh(CubeDeformation.NONE, 0.0F);
        PartDefinition partDefinition = meshdefinition.getRoot();

        // PORT26 FIX (z-fighting "belly" of the field scarecrow): 1.21.1 overrode
        // renderToBuffer and drew ONLY the custom parts below — the vanilla humanoid
        // leftovers were baked into the tree but never rendered. In 26.1
        // Model#renderToBuffer is final and submits the WHOLE root tree, so the leftover
        // vanilla "body" cube (addBox(-4,0,-2, 8,12,4) at texOffs(16,16), z planes -2..2 —
        // exactly coplanar with the custom torso, sampling the same texture region)
        // rendered on top of the torso and the belly center flickered (z-fight).
        // Same for the vanilla "hat" (child inherited by the replaced "head" through
        // PartDefinition#addOrReplaceChild child inheritance — it would draw an inflated
        // 8x8x8 shell around the head). Clear both leftovers with empty cube lists
        // (vanilla pattern, cf. HumanoidModel#createBabyArmorMesh) to restore the exact
        // 1.21.1 part set: no geometry from "body"/"hat".
        partDefinition.clearChild("body");

        PartDefinition headDefinition = partDefinition.addOrReplaceChild("head",
          CubeListBuilder.create().texOffs(0, 0).texOffs(0, 0).addBox(-8.2F, -35.6F, -4.2F, 8, 8, 8).mirror()
          , PartPose.offsetAndRotation(7F, 24F, -1F, 0F, 0.1858931F, -0.1092638F));
        headDefinition.addOrReplaceChild("hat", CubeListBuilder.create(), PartPose.ZERO);

        PartDefinition postDefinition = partDefinition.addOrReplaceChild("post",
          CubeListBuilder.create().texOffs(0, 32).addBox(-1F, -16F, -1F, 2, 16, 2).mirror()
          , PartPose.offset(0F, 24F, 0F));

        PartDefinition leftArmPegDefinition = partDefinition.addOrReplaceChild("leftArmPeg",
          CubeListBuilder.create().texOffs(9, 33).addBox(23.5F, 1F, -1F, 2, 2, 2).mirror()
          , PartPose.offsetAndRotation(7F, 24F, 0F,  0F, 0F, -1.351339F));

        PartDefinition rightArmPegDefinition = partDefinition.addOrReplaceChild("rightArmPeg",
          CubeListBuilder.create().texOffs(9, 33).addBox(-28F, 15.8F, -1F, 2, 2, 2).mirror()
          , PartPose.offsetAndRotation(7F, 24F, 0F,  0F, 0F, 1.351339F));

        PartDefinition torsoDefinition = partDefinition.addOrReplaceChild("torso",
          CubeListBuilder.create().texOffs(16, 16).addBox(-10.3F, -27.6F, -2F, 8, 12, 4).mirror()
          , PartPose.offsetAndRotation(7F, 24F, 0F, 0F, 0F, -0.0349066F));

        PartDefinition rightLegPegDefinition = partDefinition.addOrReplaceChild("rightLegPeg",
          CubeListBuilder.create().texOffs(9, 33).addBox(-11F, -4F, -1F, 2, 2, 2).mirror()
          , PartPose.offsetAndRotation(7F, 24F, 0F, 0F, 0F, 0.0872665F));

        PartDefinition leftLegPegDefinition = partDefinition.addOrReplaceChild("leftLegPeg",
          CubeListBuilder.create().texOffs(9, 33).addBox(-4.5F, -5F, -1F, 2, 2, 2).mirror()
          , PartPose.offsetAndRotation(7F, 24F, 0F, 0F, 0F, -0.0872665F));

        PartDefinition leftArmDefinition = partDefinition.addOrReplaceChild("left_arm",
          CubeListBuilder.create().texOffs(40, 16).addBox(22.5F, -10F, -1.99F, 4, 12, 4).mirror()
          , PartPose.offsetAndRotation(7F, 24F, 0F, 0F, 0F, -1.351339F));

        PartDefinition rightArmDefinition = partDefinition.addOrReplaceChild("right_arm",
          CubeListBuilder.create().texOffs(40, 16).addBox(-29F, 4.8F, -1.99F, 4, 12, 4).mirror()
          , PartPose.offsetAndRotation(7F, 24F, 0F, 0F, 0F, 1.351339F));

        PartDefinition rightLegDefinition = partDefinition.addOrReplaceChild("right_leg",
          CubeListBuilder.create().texOffs(0, 16).addBox(-12F, -15F, -1.99F, 4, 12, 4).mirror()
          , PartPose.offsetAndRotation(7F, 24F, 0F, 0F, 0F, 0.0872665F));

        PartDefinition leftLegDefinition = partDefinition.addOrReplaceChild("left_leg",
          CubeListBuilder.create().texOffs(0, 16).addBox(-5.5F, -16F, -1.98F, 4, 12, 4).mirror()
          , PartPose.offsetAndRotation(7F, 24F, 0F, 0F, 0F, -0.0872665F));

        return LayerDefinition.create(meshdefinition,  128,  64 );
    }
}
